<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="in.meenasubramanian.kaithari.TestCreateUser" time="5.465" tests="8" errors="0" skipped="0" failures="8">
  <properties>
    <property name="java.specification.version" value="17"/>
    <property name="sun.cpu.isalist" value="amd64"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.class.path" value="C:\software\eclipse_IDE_workspace\kaithari\target\test-classes;C:\software\eclipse_IDE_workspace\kaithari\target\classes;C:\Users\MeenaSubramanian\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.8.2\junit-jupiter-api-5.8.2.jar;C:\Users\MeenaSubramanian\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;C:\Users\MeenaSubramanian\.m2\repository\org\junit\platform\junit-platform-commons\1.8.2\junit-platform-commons-1.8.2.jar;C:\Users\MeenaSubramanian\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\MeenaSubramanian\.m2\repository\mysql\mysql-connector-java\8.0.28\mysql-connector-java-8.0.28.jar;C:\Users\MeenaSubramanian\.m2\repository\com\google\protobuf\protobuf-java\3.11.4\protobuf-java-3.11.4.jar;C:\Users\MeenaSubramanian\.m2\repository\io\github\cdimascio\java-dotenv\5.2.2\java-dotenv-5.2.2.jar;C:\Users\MeenaSubramanian\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.4.0\kotlin-stdlib-1.4.0.jar;C:\Users\MeenaSubramanian\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.4.0\kotlin-stdlib-common-1.4.0.jar;C:\Users\MeenaSubramanian\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;"/>
    <property name="java.vm.vendor" value="Eclipse Adoptium"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="user.variant" value=""/>
    <property name="java.vendor.url" value="https://adoptium.net/"/>
    <property name="user.timezone" value="Asia/Calcutta"/>
    <property name="os.name" value="Windows 11"/>
    <property name="java.vm.specification.version" value="17"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="user.country" value="IN"/>
    <property name="sun.boot.library.path" value="C:\software\eclipse\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.6.v20230204-1729\jre\bin"/>
    <property name="sun.java.command" value="C:\Users\MEENAS~1\AppData\Local\Temp\surefire10577879969137949556\surefirebooter15485277877728860857.jar C:\Users\MeenaSubramanian\AppData\Local\Temp\surefire10577879969137949556 2023-07-25T12-15-09_155-jvmRun1 surefire17990029817187251587tmp surefire_07458333644451267444tmp"/>
    <property name="jdk.debug" value="release"/>
    <property name="surefire.test.class.path" value="C:\software\eclipse_IDE_workspace\kaithari\target\test-classes;C:\software\eclipse_IDE_workspace\kaithari\target\classes;C:\Users\MeenaSubramanian\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.8.2\junit-jupiter-api-5.8.2.jar;C:\Users\MeenaSubramanian\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;C:\Users\MeenaSubramanian\.m2\repository\org\junit\platform\junit-platform-commons\1.8.2\junit-platform-commons-1.8.2.jar;C:\Users\MeenaSubramanian\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\MeenaSubramanian\.m2\repository\mysql\mysql-connector-java\8.0.28\mysql-connector-java-8.0.28.jar;C:\Users\MeenaSubramanian\.m2\repository\com\google\protobuf\protobuf-java\3.11.4\protobuf-java-3.11.4.jar;C:\Users\MeenaSubramanian\.m2\repository\io\github\cdimascio\java-dotenv\5.2.2\java-dotenv-5.2.2.jar;C:\Users\MeenaSubramanian\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.4.0\kotlin-stdlib-1.4.0.jar;C:\Users\MeenaSubramanian\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.4.0\kotlin-stdlib-common-1.4.0.jar;C:\Users\MeenaSubramanian\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="C:\Users\MeenaSubramanian"/>
    <property name="user.language" value="en"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.version.date" value="2023-01-17"/>
    <property name="java.home" value="C:\software\eclipse\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.6.v20230204-1729\jre"/>
    <property name="file.separator" value="\"/>
    <property name="style.color" value="always"/>
    <property name="basedir" value="C:\software\eclipse_IDE_workspace\kaithari"/>
    <property name="java.vm.compressedOopsMode" value="32-bit"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="surefire.real.class.path" value="C:\Users\MEENAS~1\AppData\Local\Temp\surefire10577879969137949556\surefirebooter15485277877728860857.jar"/>
    <property name="user.script" value=""/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="java.runtime.version" value="17.0.6+10"/>
    <property name="user.name" value="MeenaSubramanian"/>
    <property name="path.separator" value=";"/>
    <property name="os.version" value="10.0"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="file.encoding" value="Cp1252"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="java.vendor.version" value="Temurin-17.0.6+10"/>
    <property name="localRepository" value="C:\Users\MeenaSubramanian\.m2\repository"/>
    <property name="java.vendor.url.bug" value="https://github.com/adoptium/adoptium-support/issues"/>
    <property name="java.io.tmpdir" value="C:\Users\MEENAS~1\AppData\Local\Temp\"/>
    <property name="java.version" value="17.0.6"/>
    <property name="user.dir" value="C:\software\eclipse_IDE_workspace\kaithari"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="native.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\software\eclipse\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.6.v20230204-1729\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/software/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.6.v20230204-1729/jre/bin/server;C:/software/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.6.v20230204-1729/jre/bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\MeenaSubramanian\AppData\Local\Microsoft\WindowsApps;C:\Users\MeenaSubramanian\AppData\Local\GitHubDesktop\bin;C:\Users\MeenaSubramanian\AppData\Local\Programs\Microsoft VS Code\bin;;C:\software\eclipse;;."/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.vendor" value="Eclipse Adoptium"/>
    <property name="java.vm.version" value="17.0.6+10"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="61.0"/>
  </properties>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithPasswordNull" classname="in.meenasubramanian.kaithari.TestCreateUser" time="0">
    <failure message="Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown." type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithPasswordNull(TestCreateUser.java:113)
</failure>
  </testcase>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithFirstnameNull" classname="in.meenasubramanian.kaithari.TestCreateUser" time="0">
    <failure message="Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown." type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithFirstnameNull(TestCreateUser.java:153)
</failure>
  </testcase>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithValidDataInput" classname="in.meenasubramanian.kaithari.TestCreateUser" time="3.152">
    <failure message="Unexpected exception thrown: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column &apos;first_name&apos; in &apos;field list&apos; (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: &quot;insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)&quot;, BindVars: {REDACTED}" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithValidDataInput(TestCreateUser.java:28)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:77)
	at in.meenasubramanian.kaithari.serviece.UserServiece.create(UserServiece.java:18)
	at in.meenasubramanian.kaithari.TestCreateUser.lambda$0(TestCreateUser.java:29)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 16 more
Caused by: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:70)
	... 19 more
</failure>
    <system-out><![CDATA[target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
]]></system-out>
    <system-err><![CDATA[java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:70)
	at in.meenasubramanian.kaithari.serviece.UserServiece.create(UserServiece.java:18)
	at in.meenasubramanian.kaithari.TestCreateUser.lambda$0(TestCreateUser.java:29)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithValidDataInput(TestCreateUser.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.junit.PojoTestSet.executeTestMethod(PojoTestSet.java:146)
	at org.apache.maven.surefire.junit.PojoTestSet.executeTestMethods(PojoTestSet.java:108)
	at org.apache.maven.surefire.junit.PojoTestSet.execute(PojoTestSet.java:89)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:140)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]></system-err>
  </testcase>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithEmailNull" classname="in.meenasubramanian.kaithari.TestCreateUser" time="1.18">
    <failure message="Unexpected exception type thrown ==&gt; expected: &lt;in.meenasubramanian.kaithari.exception.ValidationException&gt; but was: &lt;java.lang.RuntimeException&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <in.meenasubramanian.kaithari.exception.ValidationException> but was: <java.lang.RuntimeException>
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithEmailNull(TestCreateUser.java:51)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:77)
	at in.meenasubramanian.kaithari.serviece.UserServiece.create(UserServiece.java:18)
	at in.meenasubramanian.kaithari.TestCreateUser.lambda$2(TestCreateUser.java:61)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 16 more
Caused by: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:70)
	... 19 more
]]></failure>
    <system-out><![CDATA[target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
]]></system-out>
    <system-err><![CDATA[java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:70)
	at in.meenasubramanian.kaithari.serviece.UserServiece.create(UserServiece.java:18)
	at in.meenasubramanian.kaithari.TestCreateUser.lambda$2(TestCreateUser.java:61)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithEmailNull(TestCreateUser.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.junit.PojoTestSet.executeTestMethod(PojoTestSet.java:146)
	at org.apache.maven.surefire.junit.PojoTestSet.executeTestMethods(PojoTestSet.java:108)
	at org.apache.maven.surefire.junit.PojoTestSet.execute(PojoTestSet.java:89)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:140)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]></system-err>
  </testcase>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithPasswordEmpty" classname="in.meenasubramanian.kaithari.TestCreateUser" time="0.001">
    <failure message="Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown." type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithPasswordEmpty(TestCreateUser.java:93)
</failure>
  </testcase>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithFirstnameEmpty" classname="in.meenasubramanian.kaithari.TestCreateUser" time="0">
    <failure message="Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown." type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Expected in.meenasubramanian.kaithari.exception.ValidationException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithFirstnameEmpty(TestCreateUser.java:131)
</failure>
  </testcase>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithInvalidData" classname="in.meenasubramanian.kaithari.TestCreateUser" time="0.001">
    <failure message="expected: &lt;true&gt; but was: &lt;false&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithInvalidData(TestCreateUser.java:44)
]]></failure>
  </testcase>
  <testcase name="in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithEmailEmpty" classname="in.meenasubramanian.kaithari.TestCreateUser" time="1.13">
    <failure message="Unexpected exception type thrown ==&gt; expected: &lt;in.meenasubramanian.kaithari.exception.ValidationException&gt; but was: &lt;java.lang.RuntimeException&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <in.meenasubramanian.kaithari.exception.ValidationException> but was: <java.lang.RuntimeException>
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithEmailEmpty(TestCreateUser.java:72)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:77)
	at in.meenasubramanian.kaithari.serviece.UserServiece.create(UserServiece.java:18)
	at in.meenasubramanian.kaithari.TestCreateUser.lambda$3(TestCreateUser.java:82)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 16 more
Caused by: java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:70)
	... 19 more
]]></failure>
    <system-out><![CDATA[target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
]]></system-out>
    <system-err><![CDATA[java.sql.SQLSyntaxErrorException: target: mynew_project.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'first_name' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: 2cc1s8ps3vkbs6uw2o0r): Sql: "insert into users(first_name, last_name, email, `password`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* VARCHAR */, :vtg4 /* VARCHAR */)", BindVars: {REDACTED}
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
	at in.meenasubramanian.kaithari.dao.UserDAO.create(UserDAO.java:70)
	at in.meenasubramanian.kaithari.serviece.UserServiece.create(UserServiece.java:18)
	at in.meenasubramanian.kaithari.TestCreateUser.lambda$3(TestCreateUser.java:82)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at in.meenasubramanian.kaithari.TestCreateUser.testCreateUserWithEmailEmpty(TestCreateUser.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.junit.PojoTestSet.executeTestMethod(PojoTestSet.java:146)
	at org.apache.maven.surefire.junit.PojoTestSet.executeTestMethods(PojoTestSet.java:108)
	at org.apache.maven.surefire.junit.PojoTestSet.execute(PojoTestSet.java:89)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:140)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]></system-err>
  </testcase>
</testsuite>